Домашняя работа #3
FeRoXXX/ShiftHomeworks pull request #3
Opened 2024-04-26 12:01 UTC by FeRoXXX

Создал дизайн с различными элементами UI

2024-04-27 07:47 UTC, rmaximov commented
Всё залито одним коммитом. Хорошая практика делать коммиты малыми и атомарными

2024-04-27 09:45 UTC, rmaximov requested changes

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/App/AppDelegate.swift
> +    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
минор: в app/scene delegate если код не использутся, можно с легкостью его удалять

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/DeveloperSkills/DeveloperSkills.swift
> +    var dataManager : DataManager!
Такой код очень опасный, force unwrap может привести к крашам, если его правильно не обработать в коде. Чтобы снизить потенциальный риск можно сделать dataManager опциональным, либо прокидывать его уже готовым
Ну и раз написал протокол, то хорошо бы его и использовать как тип

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/DeveloperSkills/DeveloperSkills.swift
> +            generalInformationTextView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 20),
Чтобы не было магических констант, их лучше выносить в отдельную сущность и называть осмысленно. Таким образом код становится понятнее

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/DeveloperSkills/DeveloperSkills.swift
> +        generalInformationTextView.attributedText = NSAttributedString(string: generalInformation.rawValue, attributes: [.font : UIFont.systemFont(ofSize: 14), .foregroundColor : UIColor.white])
не только константы, но и в принципе любые значения, которые повторяются кандидаты на вынос во что-то отдельное

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/DeveloperSkills/DeveloperSkills.swift
> +        self.present(learningResultAlert, animated: true)
минор: если везде пишешь без self, то можно и здесь от него отказаться. Свифт позволяет

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/Model/Model.swift
> +enum Model: String, CaseIterable {
Model очень общее название. В рамках данного проекта не сильно критично, пока. Именовать сущности стоит так, чтобы они отражали что они делают и для чего. 
Если вдруг нам придется добавить 2 сущность модели, то станет критично

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/Model/Model.swift
> +    case profilePhoto = "profilePhoto"
Неплохой вариант хранения данных, но enum с case всё же больше для однотипных связанных значений. У тебя хороший вариант реализации `enum Hobby`.
 А здесь можно использовать enum как контейнер для констант, например 
```swift
enum Model { 
   static let firstAndLastName = "Александр Федоткин"
}
```
Ещё можешь рассмотреть хранение данных в `struct` и там появится возможность прокидывать данные через инициализатор, соответственно создавать модели с различным набором данных

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/Model/Model.swift
> +class DataManager : IDataManagerProtocol {
1. минор: лишний пробел перед двоеточием
2. минор №2: название протокола, если идет с `I` вначале, то можно не писать в конце Protocol. Это именование пришло из java и I это interface, что равнозначно протоколу 
3. Очень хорошо что используешь протокол
4. Стоит придерживаться правила 1 файл - 1 сущность

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/Model/Model.swift
> +        for (index, element) in Model.allCases.enumerated() {
FYI: для for in есть прикольный синтаксический сахар for in where https://www.hackingwithswift.com/example-code/language/how-to-filter-a-loop-using-a-where-clause, можно избавиться от if внутри for

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/Model/Model.swift
> +        case Model.Hobby.guitar.rawValue:
Что-то тут намудрено сильно, кмк. Но намудрено из-за реализации модели. Как её переделаешь, этот код изменится.

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/MyHobby/MyHobby.swift
> +extension MyHobby: UIPickerViewDelegate, UIPickerViewDataSource {
хороший вынос реализации делегатов в extension. Для полноты картины можно разделить на 2:  `extension MyHobby: UIPickerViewDelegate` и `extension MyHobby: UIPickerViewDataSource`

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/MyHobby/MyHobby.swift
> +    private func setupFirstValue() {
FYI: приватные методы можно вынести в отдельный приватный extension 

```
private extension MyHobby {
...
}
```

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/MyHobby/MyHobby.swift
> +    var dataManager : DataManager!
здесь такое же замечание как в другом vc - протокол и force unwrap

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/AboutMe/AboutMe.swift
> +class AboutMe: UIViewController {
по поводу именования:
Существительными как правильно называют модели данных. В больших проектах (а это почти любой проект где >5 экранов) стараются называть классы, так чтобы в названии была понятна их деятельность
Например, `AboutMeViewController`, `AboutMePresenter` и тд

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/TabBar/TabBar.swift
> +        let aboutMeController = AboutMe()
хорошо бы было разделить по методам создание каждого view controller

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/TabBar/TabBar.swift
> +        self.view.backgroundColor = .white
минор с self и раз уже есть метод setupViewControllers, то туда же можно переместить настройку цвета

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/DeveloperSkills/DeveloperSkills.swift
> +    var generalInformationTextView : UITextView = {
вложенных вьюхи тоже можно сделать приватными

2024-04-27 09:45 UTC, rmaximov commented on HW3/HW3/DeveloperSkills/DeveloperSkills.swift
> +    private func configureUI() {
молодец, что используешь модификаторы доступа

2024-04-29 15:15 UTC, rmaximov commented on HW3/HW3/Model/Model.swift
> +    case profilePhoto = "profilePhoto"
не стал рассматривать прокидывание данных через инициализатор?

2024-04-30 08:19 UTC, FeRoXXX commented on HW3/HW3/Model/Model.swift
> +    case profilePhoto = "profilePhoto"
Я подумал, что не очень правильно будет инициализировать хардкодные данные в модель во время выполнения программы. Могу исправить

2024-05-01 10:58 UTC, rmaximov approved these changes

2024-05-01 11:03 UTC, merged